/* Generated by scripts/generate-content.mjs. Do not edit by hand. */

export const headerData = {
  links: [
    {
      text: 'Debian',
      links: [
        {
          text: 'Linux内核编译',
          href: '/debian/linux-kernel-build',
        },
        {
          text: '常用命令',
          href: '/debian/common-commands',
        },
        {
          text: 'Tmux && Screen',
          href: '/debian/tmux-screen',
        },
        {
          text: 'Python',
          href: '/debian/python',
        },
        {
          text: 'WireGuard',
          href: '/debian/wireguard',
        },
        {
          text: 'ACME证书',
          href: '/debian/acme-certs',
        },
        {
          text: 'Docker',
          href: '/debian/docker',
        },
        {
          text: 'AdGuardHome',
          href: '/debian/adguardhome',
        },
        {
          text: '硬盘挂载',
          href: '/debian/disk-mount',
        },
        {
          text: 'Kea DHCP Server',
          href: '/debian/kea-dhcp-server',
        },
        {
          text: '命令示例tar tee find',
          href: '/debian/tar-tee-find',
        },
      ],
    },
    {
      text: 'PVE',
      links: [
        {
          text: '配置',
          href: '/pve/config',
        },
        {
          text: '导入磁盘镜像',
          href: '/pve/import-disk',
        },
        {
          text: '磁盘RDM直通',
          href: '/pve/disk-rdm',
        },
        {
          text: 'ZFS',
          href: '/pve/zfs',
        },
        {
          text: 'PVE ASPM设置',
          href: '/pve/pve-aspm',
        },
        {
          text: '虚拟机管理',
          href: '/pve/vm-management',
        },
      ],
    },
    {
      text: 'VyOS配置',
      links: [
        {
          text: '安装',
          href: '/vyos/install',
        },
        {
          text: '网口配置',
          href: '/vyos/interfaces',
        },
        {
          text: '设置lan',
          href: '/vyos/lan',
        },
        {
          text: '设置时区',
          href: '/vyos/timezone',
        },
        {
          text: '设置wan',
          href: '/vyos/wan',
        },
        {
          text: 'DNS',
          href: '/vyos/dns',
        },
        {
          text: '防火墙',
          href: '/vyos/firewall',
        },
        {
          text: '访问192.168.1.1',
          href: '/vyos/access-192-168-1-1',
        },
        {
          text: '指定ipv6放行',
          href: '/vyos/ipv6-allow',
        },
        {
          text: '静态ip',
          href: '/vyos/static-ip',
        },
        {
          text: 'WAN DHCP',
          href: '/vyos/wan-dhcp',
        },
        {
          text: '流量整形',
          href: '/vyos/traffic-shaping',
        },
        {
          text: 'SSH密钥',
          href: '/vyos/ssh-key',
        },
      ],
    },
    {
      text: 'Windows',
      links: [
        {
          text: 'MD5/WIN2022激活',
          href: '/windows/md5-win2022',
        },
        {
          text: 'ADB命令',
          href: '/windows/adb',
        },
        {
          text: '网络命令',
          href: '/windows/network',
        },
      ],
    },
    {
      text: '下载',
      links: [
        {
          text: '下载总览',
          href: '/downloads',
        },
        {
          text: 'Debian脚本',
          href: '/downloads/debian-scripts',
        },
        {
          text: 'Windows工具',
          href: '/downloads/windows-tools',
        },
        {
          text: '注册表文件',
          href: '/downloads/registry-files',
        },
        {
          text: '图片',
          href: '/downloads/pictures',
        },
      ],
    },
  ],
  actions: [
    {
      text: '下载',
      href: '/downloads',
    },
  ],
};

export const footerData = {
  links: [
    {
      title: 'Debian',
      links: [
        {
          text: 'Linux内核编译',
          href: '/debian/linux-kernel-build',
        },
        {
          text: '常用命令',
          href: '/debian/common-commands',
        },
        {
          text: 'Tmux && Screen',
          href: '/debian/tmux-screen',
        },
        {
          text: 'Python',
          href: '/debian/python',
        },
        {
          text: 'WireGuard',
          href: '/debian/wireguard',
        },
        {
          text: 'ACME证书',
          href: '/debian/acme-certs',
        },
      ],
    },
    {
      title: 'PVE',
      links: [
        {
          text: '配置',
          href: '/pve/config',
        },
        {
          text: '导入磁盘镜像',
          href: '/pve/import-disk',
        },
        {
          text: '磁盘RDM直通',
          href: '/pve/disk-rdm',
        },
        {
          text: 'ZFS',
          href: '/pve/zfs',
        },
        {
          text: 'PVE ASPM设置',
          href: '/pve/pve-aspm',
        },
        {
          text: '虚拟机管理',
          href: '/pve/vm-management',
        },
      ],
    },
    {
      title: 'Windows',
      links: [
        {
          text: 'MD5/WIN2022激活',
          href: '/windows/md5-win2022',
        },
        {
          text: 'ADB命令',
          href: '/windows/adb',
        },
        {
          text: '网络命令',
          href: '/windows/network',
        },
      ],
    },
    {
      title: '下载',
      links: [
        {
          text: '下载总览',
          href: '/downloads',
        },
        {
          text: 'Debian脚本',
          href: '/downloads/debian-scripts',
        },
        {
          text: 'Windows工具',
          href: '/downloads/windows-tools',
        },
        {
          text: '注册表文件',
          href: '/downloads/registry-files',
        },
        {
          text: '图片',
          href: '/downloads/pictures',
        },
      ],
    },
  ],
  secondaryLinks: [
    {
      text: '首页',
      href: '/',
    },
    {
      text: '下载',
      href: '/downloads',
    },
  ],
  socialLinks: [],
  footNote: '',
};
